apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-gl-onprem-ua6ohvf1pc6zb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-gl-onprem-ua6ohvf1pc6zb
    app.kubernetes.io/part-of: application-gl-onprem-nkmfcrubnjcvv
  name: component-gl-onprem-ua6ohvf1pc6zb
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-gl-onprem-ua6ohvf1pc6zb
status:
  loadBalancer: {}
